// <auto-generated />
using DataAccessLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(CarDBContext))]
    partial class CarDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLibrary.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasMaxLength(50);

                    b.Property<string>("Color")
                        .HasMaxLength(50);

                    b.Property<string>("Fuel")
                        .HasMaxLength(50);

                    b.Property<string>("FullModelName")
                        .HasMaxLength(50);

                    b.Property<string>("GearBox")
                        .HasMaxLength(50);

                    b.Property<string>("ProductionYear")
                        .HasMaxLength(50);

                    b.HasKey("CarId")
                        .HasName("PK_Contact");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
